/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f7f9fb",
        "primary": "#002046",
        "surface-container-high": "#e6e8ea",
        "on-surface-variant": "#44474e",
        "error-container": "#ffdad6",
        "secondary": "#775a19",
        "on-secondary": "#ffffff",
        "tertiary": "#162132",
        "tertiary-fixed": "#d8e3fa",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#465f88",
        "on-tertiary-container": "#949fb4",
        "primary-fixed-dim": "#aec7f7",
        "secondary-container": "#fed488",
        "inverse-primary": "#aec7f7",
        "primary-fixed": "#d6e3ff",
        "primary-container": "#1b365d",
        "on-secondary-container": "#785a1a",
        "surface-dim": "#d8dadc",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#5d4201",
        "surface-container-low": "#f2f4f6",
        "outline": "#74777f",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "on-primary-container": "#87a0cd",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffdea5",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#001b3d",
        "on-tertiary-fixed": "#111c2c",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#261900",
        "secondary-fixed-dim": "#e9c176",
        "on-surface": "#191c1e",
        "outline-variant": "#c4c6cf",
        "on-primary-fixed-variant": "#2e476f",
        "tertiary-container": "#2b3648",
        "tertiary-fixed-dim": "#bcc7dd",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ['Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif']
      }
    },
  },
  plugins: [],
}
